### ISSUE TITLE
Create a new issues

### ISSUE THREAD

**Issue by hours10000** [hours10000/github-slideshow#2]
### This is an issue title
* issues's text supported markdown.

**Comment by chrispine15** [comment]
hello everyone.i'm trying to package my kivy app for andriod using the buildozer method but i keep getting the following..
# Check configuration tokens
# Ensure build layout
# Create directory /home/chrispine/Documents/programming/bin
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian 'dpkg' package management program version 1.19.0.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool
# Install platform
# Run '/usr/bin/python3 -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\''
# Cwd None
# Apache ANT found at /home/chrispine/.buildozer/android/platform/apache-ant-1.9.4
# Android SDK found at /home/chrispine/.buildozer/android/platform/android-sdk
# Android NDK is missing, downloading
# Downloading https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip
Traceback (most recent call last):
  File "/usr/local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.40.dev0', 'console_scripts', 'buildozer')()
  File "/usr/local/lib/python3.6/dist-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/buildozer/__init__.py", line 1062, in run_command
    self.target.run_commands(args)
  File "/usr/local/lib/python3.6/dist-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/usr/local/lib/python3.6/dist-packages/buildozer/target.py", line 102, in cmd_debug
    self.buildozer.prepare_for_build()
  File "/usr/local/lib/python3.6/dist-packages/buildozer/__init__.py", line 186, in prepare_for_build
    self.target.install_platform()
  File "/usr/local/lib/python3.6/dist-packages/buildozer/targets/android.py", line 597, in install_platform
    self._install_android_ndk()
  File "/usr/local/lib/python3.6/dist-packages/buildozer/targets/android.py", line 394, in _install_android_ndk
    cwd=self.buildozer.global_platform_dir)
  File "/usr/local/lib/python3.6/dist-packages/buildozer/__init__.py", line 707, in download
    urlretrieve(url, filename, report_hook)
  File "/usr/lib/python3.6/urllib/request.py", line 1819, in retrieve
    block = fp.read(bs)
  File "/usr/lib/python3.6/tempfile.py", line 624, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/usr/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2292)
oh and i recently changed my os from windows to ubuntu 18.04 for the said purpose.so far i have repeated  this for a good number of times but keep getting the same thing and  i have uninstalled buildozer and reinstalled it, I even reinstalled my ubunt 18.04 three times now but still...
to the developer who have done this before can you let me know which linux distro you used to if you do not run into this problem cause this ubuntu 18.04 seems to me to be the problem. i stand to be corrected!
can anyone help me solve this...
thanks in advance.
chris.

**Comment by hours10000** [comment]
> hello everyone.i'm trying to package my kivy app for andriod using the buildozer method but i keep getting the following..
> 
> # Check configuration tokens
> # Ensure build layout
> # Create directory /home/chrispine/Documents/programming/bin
> # Check configuration tokens
> # Read available permissions from api-versions.xml
> # Preparing build
> # Check requirements for android
> # Run 'dpkg --version'
> # Cwd None
> Debian 'dpkg' package management program version 1.19.0.5 (amd64).
> This is free software; see the GNU General Public License version 2 or
> later for copying conditions. There is NO warranty.
> 
> # Search for Git (git)
> # -> found at /usr/bin/git
> # Search for Cython (cython)
> # -> found at /usr/bin/cython
> # Search for Java compiler (javac)
> # -> found at /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
> # Search for Java keytool (keytool)
> # -> found at /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool
> # Install platform
> # Run '/usr/bin/python3 -m pip install -q --user 'appdirs' 'colorama>=0.3.3' 'jinja2' 'six' 'enum34; python_version<"3.4"' 'sh>=1.10; sys_platform!="nt"''
> # Cwd None
> # Apache ANT found at /home/chrispine/.buildozer/android/platform/apache-ant-1.9.4
> # Android SDK found at /home/chrispine/.buildozer/android/platform/android-sdk
> # Android NDK is missing, downloading
> # Downloading https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip
> Traceback (most recent call last):
> File "/usr/local/bin/buildozer", line 11, in 
> load_entry_point('buildozer==0.40.dev0', 'console_scripts', 'buildozer')()
> File "/usr/local/lib/python3.6/dist-packages/buildozer/scripts/client.py", line 13, in main
> Buildozer().run_command(sys.argv[1:])
> File "/usr/local/lib/python3.6/dist-packages/buildozer/**init**.py", line 1062, in run_command
> self.target.run_commands(args)
> File "/usr/local/lib/python3.6/dist-packages/buildozer/target.py", line 92, in run_commands
> func(args)
> File "/usr/local/lib/python3.6/dist-packages/buildozer/target.py", line 102, in cmd_debug
> self.buildozer.prepare_for_build()
> File "/usr/local/lib/python3.6/dist-packages/buildozer/**init**.py", line 186, in prepare_for_build
> self.target.install_platform()
> File "/usr/local/lib/python3.6/dist-packages/buildozer/targets/android.py", line 597, in install_platform
> self._install_android_ndk()
> File "/usr/local/lib/python3.6/dist-packages/buildozer/targets/android.py", line 394, in _install_android_ndk
> cwd=self.buildozer.global_platform_dir)
> File "/usr/local/lib/python3.6/dist-packages/buildozer/**init**.py", line 707, in download
> urlretrieve(url, filename, report_hook)
> File "/usr/lib/python3.6/urllib/request.py", line 1819, in retrieve
> block = fp.read(bs)
> File "/usr/lib/python3.6/tempfile.py", line 624, in func_wrapper
> return func(*args, **kwargs)
> File "/usr/lib/python3.6/http/client.py", line 449, in read
> n = self.readinto(b)
> File "/usr/lib/python3.6/http/client.py", line 493, in readinto
> n = self.fp.readinto(b)
> File "/usr/lib/python3.6/socket.py", line 586, in readinto
> return self._sock.recv_into(b)
> File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
> return self.read(nbytes, buffer)
> File "/usr/lib/python3.6/ssl.py", line 874, in read
> return self._sslobj.read(len, buffer)
> File "/usr/lib/python3.6/ssl.py", line 631, in read
> v = self._sslobj.read(len, buffer)
> ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2292)
> oh and i recently changed my os from windows to ubuntu 18.04 for the said purpose.so far i have repeated this for a good number of times but keep getting the same thing and i have uninstalled buildozer and reinstalled it, I even reinstalled my ubunt 18.04 three times now but still...
> to the developer who have done this before can you let me know which linux distro you used to if you do not run into this problem cause this ubuntu 18.04 seems to me to be the problem. i stand to be corrected!
> can anyone help me solve this...
> thanks in advance.
> chris.

robot?
